"""User-facing wkst preferences captured by the install menu.

The package manifest decides what gets installed. This module stores small
per-machine choices that are not package-manager state, such as whether the
shell should show a welcome image. Shell startup can consume this file later
without changing the install pipeline again.
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

from wkst.logging import log


@dataclass(frozen=True)
class InstallPreferences:
    """Optional preferences selected during interactive installation."""

    welcome_image: str | None = None

    @property
    def has_values(self) -> bool:
        return self.welcome_image is not None


def write_preferences(home: Path, preferences: InstallPreferences, *, dry_run: bool) -> None:
    """Persist preferences to ``~/.config/wkst/settings.toml``."""
    if not preferences.has_values:
        return

    path = home / ".config" / "wkst" / "settings.toml"
    content = _render_preferences(preferences)
    if dry_run:
        log.info(f"dry-run: would write install preferences to {path}")
        return

    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    log.success(f"Wrote install preferences to {path}")


def _render_preferences(preferences: InstallPreferences) -> str:
    lines = [
        "# Generated by `wkst install --menu`.",
        "# Per-machine preferences; safe to edit by hand.",
        "",
        "[shell]",
    ]
    if preferences.welcome_image is not None:
        escaped = preferences.welcome_image.replace("\\", "\\\\").replace('"', '\\"')
        lines.append(f'welcome_image = "{escaped}"')
    return "\n".join(lines).rstrip() + "\n"
